name: dropout-env
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - colorama==0.4.6
  - numpy==1.26.4
  - optuna==4.1.0
  - pyfiglet==0.8.post1
  - pandas==2.1.4
  - scikit-learn==1.3.0
  - xgboost==2.1.3
